### ISSUE TITLE
list all is null

### ISSUE THREAD

**Issue by pointcache** [midworld/unity-googledrive#10]
Hello im trying to extract list of files on gdrive but im getting null

``` csharp
// Get all files.
            var listFiles = drive.ListAllFiles();
            yield return EditorCoroutine.start(listFiles);

            string[] splitpath = savepath.Split('/');
            bool found = false;
            var files = GoogleDrive.GetResult<List<GoogleDrive.File>>(listFiles);
            if (files != null)
            {
```
i have  lot of files on my account so that cant be the issue
and i successfully connect to google, so that is not a problem too

**Comment by midworld** [comment]
Hi pointcache,

You can check the occurred error by following code:
```
if (listFiles.Current is Exception)
{
   Debug.LogWarning(listFiles.Current as Exception);
}
```

Thanks.

**Comment by pointcache** [comment]
Sadly it doesnt throw any exceptions 
http://i.imgur.com/Lr1S4LW.png

it succesfully connects, and then receives null without errors.

**Comment by midworld** [comment]
Hmm OK. Then just print this value and check what it is wrong.
``Debug.Log(listFiles.Current);

**Comment by pointcache** [comment]
:) http://i.imgur.com/Zr7OVzW.png

Maybe there is something that limits my access to gdrive?
Maybe i have to turn on some functionality apart from creating OAuth keys?

**Comment by midworld** [comment]
No. If there is a problem then the api returns a error. I think EditorCoroutine ignores corutine's result.

Open this line in GoogleDriveFile.cs and inject UnityEngine.Debug.Log(_xxx_) line by line:
https://github.com/midworld/unity-googledrive/blob/5bdd033359dea8422cbc948089971b0a06231a27/Assets/GoogleDrive/GoogleDriveFile.cs#L280

I think you can find the answer.
Thanks.

**Comment by pointcache** [comment]
hello again, no it does funtion normally i outputed json keys and it states error
http://i.imgur.com/1GXFh9V.png
however it doesnt throw any error 
http://i.imgur.com/yS4iZqH.png

``` csharp GET /?code=4/4LAHyl-WBlPPE8_M4n6QWXaLoM2DzrVLCZbliSKnZjs HTTP/1.1
Accept: text/html, application/xhtml+xml, image/jxr, */*
Referer: https://accounts.google.com/o/oauth2/auth?scope=https://www.googleapis.com/auth/drive.file%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/drive.appdata&response_type=code&redirect_uri=http://localhost:9271&client_id=633620662449-mli2iu8skimlegqpi9v4nn0cjnl7k2nr.apps.googleusercontent.com
Accept-Language: en-US
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Accept-Encoding: gzip, deflate
Host: localhost:9271
Connection: Keep-Alive

**Comment by midworld** [comment]
That is weird. Did you wait for finishing auth? Attach your source code here. It is so hard to help you with just few screenshots.

**Comment by pointcache** [comment]
``` csharp 

    public static class Gdrive
    {
        public static void Upload(string user, string pass, string savepath, string filename)
        {
            EditorCoroutine.start(upload(user, pass, savepath, filename));
        }

        private static IEnumerator upload(string user, string pass, string savepath, string filename)
        {
            var drive = new GoogleDrive();
            drive.ClientID = user;
            drive.ClientSecret = pass;

            // Request authorization.
            var authorization = drive.Authorize();
            yield return EditorCoroutine.start(authorization);

            if (authorization.Current is GoogleDrive.Exception)
            {
                Debug.LogWarning(authorization.Current as GoogleDrive.Exception);
                yield break;
            }


            // Get all files.
            var listFiles = drive.ListAllFiles();
            yield return EditorCoroutine.start(listFiles);
            Debug.Log(listFiles.Current);
            if (listFiles.Current is GoogleDrive.Exception)
            {
                Debug.LogWarning(listFiles.Current as GoogleDrive.Exception);
                yield break;
            }
            string[] splitpath = savepath.Split('/');
            bool found = false;
            var files = GoogleDrive.GetResult<List<GoogleDrive.File>>(listFiles);
            if (files != null)
            {
                foreach (var file in files)
                {
                    // Download a text file and print.
                    if (file.Title == filename)
                    {
                        found = true;
                        foreach (var f in file.Parents)
                        {
                            Debug.Log(f);
                        }
                    }
                }
            }
            if (!found)
                Debug.Log("No such folder found");
            // Authorization succeeded.
            //Debug.Log("User Account: " + drive.UserAccount);
            //yield return EditorCoroutine.start(drive.UploadFile(filename +".zip", "application/zip", ));
        }

        //static bool CheckFolder(string[] path, ref int lenght, List<GoogleDrive.File> files)
        //{
        //    foreach (var file in files)
        //    {
        //        if (file.Title == path[lenght])
        //        {
        //            if(file.Parents)
        //        }
        //    }
        //}
    }

**Comment by midworld** [comment]
I think you make a unity editor function but i didn't test on that environment. Restart the editor and check `GoogleDrive.IsAuthorized` before request `ListAllFiles()`. And if the json contains 'error' you can get the details by `GetError()`. See this line: https://github.com/midworld/unity-googledrive/blob/5bdd033359dea8422cbc948089971b0a06231a27/Assets/GoogleDrive/GoogleDriveFile.cs#L310

Thanks.

**Comment by pointcache** [comment]
Well as i showed you console output, it does in fact contain error key,
but no error is thrown :|
this says there is an error http://i.imgur.com/vhiDJHb.png
aaha
it seems that the json check happens before the autorization, 
and because you have a break there it just drops the whole thing.
so i have to make it wait until user presses button - allow, right?

**Comment by midworld** [comment]
You can print the details with p.Value. Yes, wait for auth first and query later.

**Comment by pointcache** [comment]
Ok thanks for patience ill try to fix it tomorrow :)

**Comment by midworld** [comment]
No problem.

**Comment by pointcache** [comment]
Hi, today after i launched the project i no longer get login prompt and the console output looks differently.
I also made a check for authorization:
``` csharp

            while (!drive.IsAuthorized)
            {
                Debug.Log("Not authorized");
                yield return null;
            }
```
I am properly authorizing 
http://i.imgur.com/sZKht5q.png
but i still receive null when trying to get all folders.
maybe i should also wait for all folders to download?

**Comment by pointcache** [comment]
I dunno. I tried something and it seems for some reason method just goes throught the listing, without waiting for it to complete.
I guess you can say its because of some flaw of editor coroutine,
can you tell me for what purpose you wrote your plugin? Like did you really write it only for runtime?
I am really frustrated, sorry.

**Comment by pointcache** [comment]
I tried these editor coroutines as they look more sophisticated but same result https://github.com/FelixEngl/EditorCoroutines

**Comment by pointcache** [comment]
How can i just make it work? Im tryin to intercept responsed isDone, as i assumed there is something wrong with coroutines, but now i feel that they work correctly and the problem is somewhere else.

**Comment by pointcache** [comment]
Ok im giving up, i dont want to learn all your codebase for this. and to prevent others from running into my issue you have to make a big warning on Readme page :
NOT SUPPORTED IN EDITOR

**Comment by midworld** [comment]
Hi pointcache,

It is quite complicated to write editor plugin. You should think about SerializedField and etc. I think you make this plugin to work on editor(the auth code can be removed when you recompile scripts). Modifying this plugin is easier than making another one obviously. And you should read and understand when using open source.

Thanks.
