### ISSUE TITLE
How do I Authorise for Android

### ISSUE THREAD

**Issue by c4digit** [midworld/unity-googledrive#20]
Hello 

I am unsure how to change the  file "unity-googledrive / NativePlugins / Android / GoogleDrivePlugin / src / com / studio272 / googledriveplugin / GoogleDrivePlugin.java"
to modify it so I can Authorise on Android?

Are you able to instruct me on how to change the line?
 credential = GoogleAccountCredential.usingOAuth2(activity,
 "https://www.googleapis.com/auth/drive.file",
 "https://www.googleapis.com/auth/drive.appdata");

Thanking you in advance

Paul

**Comment by midworld** [comment]
I don't understand what you want clearly.

If you want more permissions, just add the permission strings to that `credential = ...` line. Or if you want modify the original java source code, modify the code as you want first, compile it to JAR library in Eclipse and replace the generated JAR file to the Unity plugin folder.

Thanks.

**Comment by c4digit** [comment]
Sorry, not great at programming. I’m more of an artist who is not afraid to do some scripting 

So before I go any further can I ask a few questions

1) Inside my Android app , can I authorise connection to the app data folder without choosing an account? So it uses the bundle ID of the app instead as authorisation, without displaying any extra pop-ups?
2) Can I directly download files bigger than 25MB without the Google drive virus scan?

Thanks for your quick response 

Paul

**Comment by chaotickid48** [comment]
i am sorry but i did not make this thread i dont know why this thread was
attached to me but i would like to know where this came from and what you
are talking about if you can contact me at this phone number (780-404-1233)
if you cant or just dont want to contact me that way just contact me here.

**Comment by midworld** [comment]
Hi Pual,

1) if your android phone has multiple accounts in Settings>Accounts>Google, you cannot avoid the popup to select the account. Because the app doesn't know what account the user wants to use.
2) I've never tried to download files have more than 25MB. And there is no content of virus scanning on Google API doc(https://developers.google.com/drive/v3/web/manage-downloads). I think there is no problem about downloading big files.

I hope it will be helpful.
Thanks.

**Comment by chaotickid48** [comment]
I am sorry but i asked when my account became part of this thread not what
accounts my android has and I also didn't how many MBs my phone can
download from so please get this tread off my account.

**Comment by chaotickid48** [comment]
I am not even a github user

**Comment by chaotickid48** [comment]
so now i am deleting these messages from my gmail and i hope not to see
this popup here anymore goodbye
