### ISSUE TITLE
SubModules

### ISSUE THREAD

**Issue by samavan** [midworld/unity-googledrive#23]
<img width="770" alt="screen shot 2017-09-05 at 11 38 51" src="https://user-images.githubusercontent.com/6184992/30042830-d81a3830-922e-11e7-89a5-8452c0ec295a.png">
Hi!

Adding your project root to my unity project as SubModules but having a bunch of error from the docs folder.

Should I remove the entire folder? Or maybe to subModules from Assets only?...

**Comment by midworld** [comment]
Hello Samaven,
Just add files in Assets directory of unity-googledrive and merge link.xml if you already have it. You don't need docs, ProjectSettings or something out of Assets directory.
Thanks.

**Comment by samavan** [comment]
ah I see... just wanted to be sure... will see if the subModule can manage subfolder also...

**Comment by midworld** [comment]
I don't think so. You need a tricky way for it(symlink or something). So I suggest you just copy-and-paste files you need. If you can add a specific directory in submodule, there still remain the issue about link.xml.
