### ISSUE TITLE
[Unity 2017.1.0f3] iOS build error

### ISSUE THREAD

**Issue by samavan** [midworld/unity-googledrive#25]
<img width="532" alt="screen shot 2017-09-05 at 12 35 33" src="https://user-images.githubusercontent.com/6184992/30044244-060e525a-9237-11e7-8c8f-4bc4453d2646.png">

A few errors on build for iOS platform :

Assets/__submodules/unity-googledrive/Assets/GoogleDrive/GoogleDriveAuthorization.cs(431,40): error CS0023: The `!' operator cannot be applied to operand of type `string'

Assets/__submodules/unity-googledrive/Assets/GoogleDrive/GoogleDriveAuthorization.cs(434,15): error CS0029: Cannot implicitly convert type `string' to `bool'

Assets/__submodules/unity-googledrive/Assets/GoogleDrive/WebViewObject.cs(52,17): error CS0029: Cannot implicitly convert type `bool' to `string'

Checked the code and it does returns string where a condition waiting for boolean... :(

**Comment by samavan** [comment]
<img width="325" alt="screen shot 2017-09-05 at 13 08 47" src="https://user-images.githubusercontent.com/6184992/30044905-6d5182da-923b-11e7-9455-5b52c55177d9.png">
Fix is easy but I am not allowed to push. :(

**Comment by midworld** [comment]
Clone this repository to your repository and 'git clone' from your account.
And you can commit and push on that. If you want to contribute you can make
pull request from your push in your repository.
