### ISSUE TITLE
[xCode 9b5] Bunch of errors...

### ISSUE THREAD

**Issue by samavan** [midworld/unity-googledrive#26]
<img width="1143" alt="screen shot 2017-09-05 at 12 59 47" src="https://user-images.githubusercontent.com/6184992/30044760-63623216-923a-11e7-8ca3-10d1b39a743f.png">
Bunch of errors occurs from Xcode... any idea?...

**Comment by midworld** [comment]
Turn off automatic ref count mode or remove 'retian' message and delete all
the release/dealloc lines.

**Comment by samavan** [comment]
Worked a charm!

Below the location for this settings for those having the same issue 👍 
<img width="864" alt="screen shot 2017-09-05 at 16 53 00" src="https://user-images.githubusercontent.com/6184992/30050961-3c6b2174-925b-11e7-98c1-274149aacd7e.png">
