### ISSUE TITLE
[Xcode 9b5] Error on app launch.

### ISSUE THREAD

**Issue by samavan** [midworld/unity-googledrive#27]
Any idea?...
<img width="1125" alt="screen shot 2017-09-05 at 17 41 45" src="https://user-images.githubusercontent.com/6184992/30052755-8879f9ea-9261-11e7-9426-4f0e27b0b1f8.png">

**Comment by midworld** [comment]
I found the issue that the new verison of Unity doesn't support turning ARC off. Please remove 'retain' and 'dealloc/remove' lines in webview source code.
 
http://answers.unity3d.com/questions/1074455/unity-ios-project-gets-crashed-when-returning-from.html
