### ISSUE TITLE
file search not working in unity

### ISSUE THREAD

**Issue by sidhants** [midworld/unity-googledrive#28]
Hi, 
I am trying to simply search for a file in my google drive for downloading through Unity eg a .pptx or even a .txt file which exists for sure.
This is the function I have and it gives no results on search. Connection to my google drive is successful and new files are created in the demo scene but search query does not work and I always get file not found for anything I try. Unity version is 2017. How do I get it to work?

IEnumerator DownloadPresentation()
	{
		Debug.Log ("download pressed");

		if (drive == null || !drive.IsAuthorized || downloadInProgress)
			yield break;

		downloadInProgress = true;
		Debug.Log ("download pressed 1");

		var list = drive.ListFilesByQueary("name = 'INSTRUCTIONS_G4 UNITY CYBERTOUCH DEMOS.txt'");
		yield return StartCoroutine(list);

		GoogleDrive.File file;
		Dictionary<string, object> data;

		if (list != null) 
		{
			var files = GoogleDrive.GetResult<List<GoogleDrive.File>> (list);
			if (files == null || files.Count > 0) {
				// Found!
				file = files [0];
				Debug.Log ("file name is " + file.Title);
			}
			else 
			{
				Debug.Log ("file not found");
				yield break;
			}				

		} 

		Debug.Log ("download finished");	
		downloadInProgress = false;	

	}

Thanks a lot. Attached the DriveTest file from the demo.
Sidhant.
[DriveTestcs.txt](https://github.com/midworld/unity-googledrive/files/1307896/DriveTestcs.txt)

**Comment by sidhants** [comment]
<img width="1467" alt="unity screenshot" src="https://user-images.githubusercontent.com/18451476/30506291-9bb58abc-9a2f-11e7-9f1d-dd27d353de4f.png">

Screenshot from inside unity fyi.
Sidhant.

**Comment by sidhants** [comment]
Also tried with no luck -
var list = drive.ListFilesByQueary("title = 'INSTRUCTIONS_G4 UNITY CYBERTOUCH DEMOS.txt'");
(as it is google drive API v2)

**Comment by midworld** [comment]
Hi sidhants,
Your file name has spaces so you should escape it yourself or using Uri.escape something like: ...G4%20UNITY%20CYBER...
Thanks.

**Comment by sidhants** [comment]
Hi midworld,
Thanks for getting back. I tried a file called Instructions.txt and still not able to search/download. Seems like something else is going on. Any information I can provide via debugging?
btw i added the authorization for full drive access in the scope as well still no luck.
drive.Scopes = new string[] {
			"https://www.googleapis.com/auth/drive",
			"https://www.googleapis.com/auth/drive.file",
			"https://www.googleapis.com/auth/userinfo.email",
			"https://www.googleapis.com/auth/drive.appdata",
		};

Thanks,
Sidhant

**Comment by midworld** [comment]
Hmm... you can print the response from Google directly with Debug.Log(response.text) in ListFilesByQueary method. Could you please share the log?

**Comment by sidhants** [comment]
actually when i tried to print the response.text, it is null even when trying to init the drive at start and i got an error attached. Attaching editor log as well
[EditorLog.txt](https://github.com/midworld/unity-googledrive/files/1308153/EditorLog.txt)
![capture](https://user-images.githubusercontent.com/18451476/30510232-b2ad8d56-9a74-11e7-9990-7e7ed8ed3804.PNG)

**Comment by midworld** [comment]
Sorry for the late response.
I saw your query string in the logs, it said: https://www.googleapis.com/drive/v2/files?q=title+%3D+'Instructions.txt'
It is not escaped completely(still it has '). Following Google document(https://developers.google.com/drive/v2/web/search-parameters), it should be: title+%3d+%27hello%27(in case of title = 'hello').
Please check it again. Thanks.

**Comment by sidhants** [comment]
No problem Kim.
I am using the same format as you have provided in the UploadText() function:
                 // Get 'my_text.txt'.
		var list = drive.ListFilesByQueary("title = 'my_text.txt'");
		yield return StartCoroutine(list);

I realized the single quote ' is not getting encoded correctly to %27. I manually tried creating the query string as below for verifying:
var list = drive.ListFilesByQueary("title = " + "%27" + "Instructions.txt" + "%27");

Even this did not work for me and the file count returned was still zero. Attaching editor log.
Any ideas ?

**Comment by sidhants** [comment]
[EditorLog.txt](https://github.com/midworld/unity-googledrive/files/1308994/EditorLog.txt)

**Comment by sidhants** [comment]
Just wondering if you are able to search any files in your drive using the same search code. Or if it is any authorization issue (like 401  error) that does not respond to the web queries.

**Comment by midworld** [comment]
in your log:
1) GET /drive/v2/files?q=title%20=%20%27Instructions.txt%27 HTTP/1.1
2) title = %27Instructions.txt%27

All URIs didn't escape correctly:
for 1) = have to be %3d
for 2) it still has spaces and also unescaped =

FYI you can test the API in the official Google API document pages:
https://developers.google.com/drive/v2/reference/files/list

Please see my screenshot. Thanks!
![image](https://user-images.githubusercontent.com/1697772/30520853-a0c4f7fa-9bf0-11e7-8df6-06e365de4844.png)

**Comment by sidhants** [comment]
Well it definitely works in the google API directly. Thanks for pointing that out (just started working with google API's sorry about that).
What I discovered is that it works in Unity 5.4 but NOT in Unity 2017. In 5.4. I am able to find the file with the exact same code:
![image](https://user-images.githubusercontent.com/18451476/30561331-7bf29214-9c6f-11e7-9cc0-a0ea4810f005.png)

**Comment by sidhants** [comment]
2017 screenshot with same code but returned list is null
![image](https://user-images.githubusercontent.com/18451476/30562064-10b86926-9c72-11e7-80b7-ced4bbb6c103.png)

**Comment by sidhants** [comment]
editor logs from both if you can take a look please.
[5_4editorLog.txt](https://github.com/midworld/unity-googledrive/files/1312072/5_4editorLog.txt)
[2017editorlog.txt](https://github.com/midworld/unity-googledrive/files/1312071/2017editorlog.txt)

Thanks a lot,
Sidhant.

**Comment by sidhants** [comment]
Spotted something....in the logs!
Observe the scopes in the screenshot below. In 2017, scope does not change to only "drive" even though in both files (DriveTest.cs and GoogleDriveAuthorization.cs) I have commented as below.  Exact same thing in 5.4 reflects the correct setting.
drive.Scopes = new string[] {
			"https://www.googleapis.com/auth/drive",
			//"https://www.googleapis.com/auth/drive.file",
			//"https://www.googleapis.com/auth/userinfo.email",
			//"https://www.googleapis.com/auth/drive.appdata",
		};
![image](https://user-images.githubusercontent.com/18451476/30567953-8f507c14-9c87-11e7-9ea3-e328ea7f9c16.png)

Any ideas how I can get the correct setting for scope in 2017? I think that will probably fix it.

**Comment by midworld** [comment]
Hmm, I just tested ListByQuery() on Unity 2017 but it works. Can change scopes and get the items by the query. See my code and screenshot.
```
	IEnumerator InitGoogleDrive()
	{
		// ...

		drive.Scopes = new string[] {
			"https://www.googleapis.com/auth/drive",
			"https://www.googleapis.com/auth/drive.appdata",
		};
		Debug.Log(string.Join(", ", drive.Scopes)); // <- check scope

		var authorization = drive.Authorize();
		yield return StartCoroutine(authorization);

		if (authorization.Current is Exception)
		{
			Debug.LogWarning(authorization.Current as Exception);
			goto finish;
		}
		else
			Debug.Log("User Account: " + drive.UserAccount);

		// ...

		{
			var a = drive.ListFilesByQueary("title='SSR'");
			yield return StartCoroutine(a);
			var b = GoogleDrive.GetResult<List<GoogleDrive.File>>(a);
			if (b != null)
			{
				foreach (var c in b) Debug.Log(c);
			}
		}
```
![image](https://user-images.githubusercontent.com/1697772/30577303-5309fc32-9d48-11e7-8728-3b14beceb8d7.png)

**Comment by sidhants** [comment]
That fixed it. I have it working. Thanks a lot. I will mark it as closed. 
One question I had was if it is possible (currently via this API) to say download a google doc ppt/excel as a pdf or images. I am working on a VR tool and integrating the drive API into it.
Thanks,
Sidhant.

**Comment by midworld** [comment]
You can export your google doc to PDF by this API: https://developers.google.com/drive/v2/reference/files/export

Thanks!
