### ISSUE TITLE
This plugin is useful if only I want to update spreadsheet data?

### ISSUE THREAD

**Issue by joecabezas** [midworld/unity-googledrive#3]
This plugin is useful if only I want to update spreadsheet data?, I do not want to manage files and folders, I just want to read from a spreadsheet and write back to it, is this possible with this plugin?

**Comment by midworld** [comment]
Hi Joe,

This plugin can read the data by binary format only(such a text or image).

So it cannot edit a spreadsheet data.

I recommend use csv(tab-split format) instead the spreadsheet format if you
really want to do that with this plugin.

Thanks.

**Comment by joecabezas** [comment]
Oh I see, thanks! :)
