### ISSUE TITLE
Exception: Authorization failed (Application name is not set)

### ISSUE THREAD

**Issue by GuillermoDoradoVide** [midworld/unity-googledrive#32]
I get this message in the console log debugging in android build:

GoogleDrive+Exception: Authorization failed.

And in the Android Device monitor I get this error:

11-28 17:40:07.718: D/Unity-GoogleDrivePlugin(28571): setUnityActivity: com.unity3d.player.UnityPlayerActivity@bed688c
11-28 17:40:07.728: D/Unity-GoogleDrivePlugin(28571): auth with accountName: userNameSample1234567AV@gmail.com
11-28 17:40:07.738: W/AbstractGoogleClient(28571): Application name is not set. Call Builder#setApplicationName.
11-28 17:40:07.738: D/Unity-GoogleDrivePlugin(28571): google drive service: com.google.api.services.drive.Drive@d81164f
11-28 17:40:07.738: E/Unity-GoogleDrivePlugin(28571): checkAuthorized: java.lang.IllegalArgumentException: the name must not be empty: null

I thought I set everything correctly (in editor works and uploads a file)

**Comment by midworld** [comment]
I think Google Drive API is changed. You should fix following line: https://github.com/midworld/unity-googledrive/blob/77cc11b8d6365716971aaa5b87feac512030656d/NativePlugins/Android/GoogleDrivePlugin/src/com/studio272/googledriveplugin/GoogleDrivePlugin.java#L168
with this fix: https://stackoverflow.com/questions/20251189/application-name-is-not-set-call-buildersetapplicationname-error
And build Java library in Eclipse and replace the JAR file in Plugins folder.

**Comment by GuillermoDoradoVide** [comment]
Going into de AppSettings on android and giving "contact permissions", then launching the app the plugin works and no warning!

**Comment by midworld** [comment]
Good. Google Drive needs saved Google accounts on the mobile phone.
