### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by jcaron144** [midworld/unity-googledrive#33]
When downloading a zip file, Unity holds onto the memory. Try downloading a 200MB file and you'll see that even after you stop the application in the editor, your memory consumption sky-rockets. If you play it again, it cumulatively adds to the memory.

**Comment by midworld** [comment]
This plugin just holds byte array for downloaded content(see https://github.com/midworld/unity-googledrive/blob/7be81c0ac570a7588d65ed8cf34ab858613b6c78/Assets/GoogleDrive/UnityWebResponse.cs#L46). It just acquires as 'Content-Length'(or using MemoryStream and dispose it). So if you don't retain the byte array anymore, GC will remove it.

Can I get more information with memory dump on debugger or something?

**Comment by jcaron144** [comment]
Thank you for the speedy response. As far as the byte array is concerned, I am not even assigning it to a variable. I am simply logging the size and then setting it to null. I am running the "DriveText.unity" scene within the GoogleDrive -> Test folder.

The only difference is that instead of downloading a ".txt" file, I am downloading a large zip file outside of the AppData folder.

Below is my customized code:

`var listFiles = drive.ListFiles(interactiveFolder);
			yield return StartCoroutine(listFiles);
			var files = GoogleDrive.GetResult<List<GoogleDrive.File>>(listFiles);

			if (files != null)
			{
				foreach (var file in files)
				{
					Debug.Log(file);

					if (file.Title == "WordWall")
					{
                        Debug.Log("Downloading..");
                        IEnumerator downloadCoroutine = drive.DownloadFile(file);
                        yield return StartCoroutine(downloadCoroutine);
						
                        byte[] data = GoogleDrive.GetResult<byte[]>(downloadCoroutine);
//                        downloadCoroutine.Reset();
                        Debug.Log(data.Length);

                        data = null;
                        downloadCoroutine = null;
					}
				}
			}
			else
			{
				Debug.LogError(listFiles.Current);
			}`

**Comment by midworld** [comment]
Your code has no problem(nullify data and downloadCoroutine). I think GC is not executed. Could you please test run following code after you release the byte array?
```
System.GC.Collect();
System.GC.WaitForPendingFinalizers();
```
or changing Unity Scene.
Thanks.

**Comment by jcaron144** [comment]
Thank you for the suggestion, I modified the above code to:
```
if (file.Title == "WordWall")
{
      Debug.Log("Downloading..");
       IEnumerator downloadCoroutine = drive.DownloadFile(file);
       yield return StartCoroutine(downloadCoroutine);
						
       byte[] data = GoogleDrive.GetResult<byte[]>(downloadCoroutine);
       Debug.Log(data.Length);

        data = null;
        downloadCoroutine = null;

        System.GC.Collect();
        System.GC.WaitForPendingFinalizers();

        yield return new WaitForSeconds(5);

        SceneManager.LoadScene(0);
}
```

Memory Before Starting program in editor:
![image](https://user-images.githubusercontent.com/31282981/33561448-a50b49fe-d8e0-11e7-82f2-0e50de8ab8a3.png)

Memory After initial start:
![image](https://user-images.githubusercontent.com/31282981/33561493-ccd939f0-d8e0-11e7-8d6d-c53c5cf9ada7.png)

Memory after Scene was reloaded:
![image](https://user-images.githubusercontent.com/31282981/33561550-f53adb24-d8e0-11e7-90e6-b0046c3fc82c.png)

Memory After Stopping the Application, Starting the application again and waiting for the scene to reload:
![image](https://user-images.githubusercontent.com/31282981/33561746-81663a8a-d8e1-11e7-911a-0d0fa38274da.png)

Unfortunately, it still seems to have the memory issue.

**Comment by midworld** [comment]
Oh, I don't know how Unity deal its memory(I think Unity doesn't release the allocated space before system has not sufficient memory same as other VM apps). You can check the real used space on Profiler memory tabs. Please check the Profiler. Thanks.

**Comment by jcaron144** [comment]
Oh, you are correct. The memory used by the editor does cap out at about 5.5GB. I was afraid that if the memory continued to increase, it would freeze the application, but that is not the case and the Profiler has a steady 22.2MB total allocation.. Thank you.
