### ISSUE TITLE
AutoConnect

### ISSUE THREAD

**Issue by Homeak** [midworld/unity-googledrive#36]
Hi,

sorry, i didn't found another way to contact you.
Is there a way to introduce in code gmail account username and password and skip authorize on every new device?

In any case, my mail:
tampei.ti@gmail.com

Thx,
Anton.

**Comment by midworld** [comment]
You can make a credential for Google services. Please read these pages: https://developers.google.com/api-client-library/python/guide/aaa_overview

Also you can acquire full permissions with the `https://mail.google.com/` scope. But the credential will revoke every 6 months.

Hope it helps you. Thanks.

**Comment by Homeak** [comment]
Thx,
i will toke a look at link.
Don't think it's easy.

Best regards.
