### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by GuillermoDoradoVide** [midworld/unity-googledrive#37]
Hi! The plugin was working fine, but when I tryed to use another GMAIL account where to upload files, errors started to appear.
- Now always pop up a browser to choose the account (and after selecting account it just freeze).
- This error appears in Unity: > System.Net.Sockets.SocketException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
I triyed using the previous configuration but the errors persists.

**Comment by midworld** [comment]
Hi, Please provide more information to clarify the problem.
- When the browser shows up, there are 2 Google accounts?
- And you choose one of them, it makes your game suspended?
- Need to see full error log.
Thanks.

**Comment by GuillermoDoradoVide** [comment]
Yes, now it shows 2 google accounts. When I choose one of them, it then ask me if I give permission. When I accept, the browser freezes. Sometimes and error localhost shows to.
<img width="960" alt="captura de pantalla 2018-01-04 18 04 02" src="https://user-images.githubusercontent.com/10259619/34575066-bad051d8-f179-11e7-9fc1-5f11b8775416.png">
Translation:
**CANNOT ACCESS THIS PAGE.
- Be sure that the direction  http://localhost:9271 is correct.**

The full error log >
System.Net.Sockets.SocketException: Solo se permite un uso de cada dirección de socket (protocolo/dirección de red/puerto)
Translation: **Only one usage of each socket address (protocol/network address/port) is normally permitted.**

  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start (Int32 backlog) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.TcpListener.Start () [0x00000] in <filename unknown>:0 
  at AuthRedirectionServer.StartServer (Int32 port) [0x00028] in C:\Users\Guillermo\Documents\TRABAJO\VRAgent\VRClass_Language\Assets\GoogleDrive\AuthRedirectionServer.cs:54 
UnityEngine.Debug:LogError(Object)
AuthRedirectionServer:StartServer(Int32) (at Assets/GoogleDrive/AuthRedirectionServer.cs:63)
<GetAuthorizationCodeAndAccessToken>c__Iterator2:MoveNext() (at Assets/GoogleDrive/GoogleDriveAuthorization.cs:474)
<Authorize>c__Iterator0:MoveNext() (at Assets/GoogleDrive/GoogleDriveAuthorization.cs:250)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<InitGoogleDrive>c__Iterator4:MoveNext() (at Assets/Code/MenuAndInterface/InteractionMenu/CameraPhotoScreenCapture/ScreenCaptureUI.cs:251)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
ScreenCaptureUI:Start() (at Assets/Code/MenuAndInterface/InteractionMenu/CameraPhotoScreenCapture/ScreenCaptureUI.cs:53)

**Comment by midworld** [comment]
Yeah, i think i've got a sense little bit.

The login watching server([GoogleDriveAuthorization.cs](https://github.com/midworld/unity-googledrive/blob/38772b8e424bc873c6aa12f9e886c9767a9ce55b/Assets/GoogleDrive/GoogleDriveAuthorization.cs)) doesn't stop by some reason I think an error occurs when it is closing or Unity bugs. So SocketException occurs because the server is already using the port 9271.

I think the server will goes down if you close Unity. If it won't, you should change the port 9271 temporarily or reset your computer.

FYI: you can check the port usage by [netstat](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows).

Thanks.

**Comment by GuillermoDoradoVide** [comment]
Okey, I solved the socket exception, but now the conexion with google  drive is not working.
I get to warning: 

FIRST 
HTTP/1.1 401 Unauthorized
Vary: Accept-Encoding
Content-Type: application/json; charset=utf-8
Date: Thu, 04 Jan 2018 18:39:12 GMT
Pragma: no-cache
Accept-Ranges: none
Expires: Mon, 01 Jan 1990 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
Server: ESF
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
X-XSS-Protection: 1; mode=block

{
  "error" : "invalid_client"
}
UnityEngine.Debug:LogWarning(Object)
Midworld.<UnityWebResponse>c__AnonStorey0:<>m__0(Object) (at Assets/GoogleDrive/UnityWebResponse.cs:317)

SECOND

GoogleDrive+Exception: invalid_client
UnityEngine.Debug:LogWarning(Object)
<InitGoogleDrive>c__Iterator4:MoveNext() (at Assets/Code/MenuAndInterface/InteractionMenu/CameraPhotoScreenCapture/ScreenCaptureUI.cs:255)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

I validated the new gmail account and user, the api and the credentials. (Repeated the installation process with the new account).

**Comment by midworld** [comment]
I think it is better to wipe old Google API Key. This library uses PlayerPrefs for saving API sign in information([here](https://github.com/midworld/unity-googledrive/blob/38772b8e424bc873c6aa12f9e886c9767a9ce55b/Assets/GoogleDrive/GoogleDriveAuthorization.cs#L128)), so you can remove this data on RegEdit path `HKCU\Software\[company name]\[product name]`. Please check [Unity Help Page](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html).

Follow [this page](https://premium.wpmudev.org/forums/topic/google-drive-401-thats-an-error-error-invalid_client-the-oauth-client-was-not-found) the client id on Google Console is the problem. Please check again the process of making new Google API key.

Thanks.

**Comment by GuillermoDoradoVide** [comment]
Okey, I deleted the data on RegEdit (and deleted all keys in playerpreferences), and used the link for the client id (using android for the OAuth Client ID instead of web) and nothing changed. Now the socket exception triggers always.

**Comment by midworld** [comment]
Hmm, as I told, the socket exception is occurred by auth listen server(run on localhost: 9271). You should check the server is running correctly(GoogleDriveAuthorization.cs).

Turn off the server instance and try to sign in again. Then you can get the log about the error. If you get the same error({"error" : "invalid_client"}), you should check your client id on Google Console. The socket exception is not important now because it's just occurred by the auth error.

So you should concern about the auth error. Please read some articles about invalid_client error. https://stackoverflow.com/questions/17166848/invalid-client-in-google-oauth2

**Comment by GuillermoDoradoVide** [comment]
Okey, I'm a bit lost. I have deleted the new gmail account I had created, and deleted the project in the old account (The one where I successfully installed and used the API). Then, I erased the playerPreferences keys, create a new gmail account and created a project, activated GoogleDrive plugin, authID, etc.
The result is this:
- 
<img width="960" alt="captura de pantalla 2018-01-06 22 12 36" src="https://user-images.githubusercontent.com/10259619/34644000-e81b6fcc-f32e-11e7-8e02-95ffa03ad500.png">
-
<img width="960" alt="captura de pantalla 2018-01-06 22 14 46" src="https://user-images.githubusercontent.com/10259619/34644017-14e37356-f32f-11e7-971a-83e905c18278.png">
- Then > 
POST /o/oauth2/token HTTP/1.1
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Charset: utf-8
Content-Type: application/x-www-form-urlencoded
Host: accounts.google.com
User-Agent: Mozilla/5.0 (Unity3d)
Content-Length: 237

code=4/AcNcf1muXeDF8nWPIu6glRtkX4e_l_SRwnRTPg0qaT0&client_id=516466942533-bago81a5jvj9aopm11acbsmsmh9gn409.apps.googleusercontent.com&client_secret=tGNLbYnrdRO2hdFmwJAo5Fbt&redirect_uri=http://localhost:9271&grant_type=authorization_code
UnityEngine.Debug:LogWarning(Object)
Midworld.<UnityWebResponse>c__AnonStorey0:<>m__0(Object) (at Assets/GoogleDrive/UnityWebResponse.cs:313)

-
HTTP/1.1 401 Unauthorized
Vary: Accept-Encoding
Content-Type: application/json; charset=utf-8
Date: Sat, 06 Jan 2018 21:09:23 GMT
Pragma: no-cache
Accept-Ranges: none
Expires: Mon, 01 Jan 1990 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
Server: ESF
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Alt-Svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35"
X-XSS-Protection: 1; mode=block

{
  "error" : "invalid_client"
}
UnityEngine.Debug:LogWarning(Object)
Midworld.<UnityWebResponse>c__AnonStorey0:<>m__0(Object) (at Assets/GoogleDrive/UnityWebResponse.cs:317)
- 

GoogleDrive+Exception: invalid_client
UnityEngine.Debug:LogWarning(Object)
<InitGoogleDrive>c__Iterator4:MoveNext() (at Assets/Code/MenuAndInterface/InteractionMenu/CameraPhotoScreenCapture/ScreenCaptureUI.cs:260)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

- I created a product name as same as project name, and redo the ID and recreate the project. Nothings works. I am missing something?

**Comment by GuillermoDoradoVide** [comment]
Key, I'm getting this warning:

- **System.IO.IOException: Read failure ---> System.Net.Sockets.SocketException:** Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder.
(**TRANSLATION > An error occurred during the connection attempt because the connected party did not respond properly after a period of time, or an error occurred in the connection established because the connected host could not respond**)

  at System.Net.Sockets.Socket.Receive (System.Byte[] buffer, Int32 offset, Int32 size, SocketFlags flags) [0x00000] in <filename unknown>:0 
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.Sockets.NetworkStream.Read (System.Byte[] buffer, Int32 offset, Int32 size) [0x00000] in <filename unknown>:0 
  at AuthRedirectionServer.Listen () [0x0015e] in C:\Users\Guillermo\Documents\TRABAJO\VRAgent\VRClass_Language\Assets\GoogleDrive\AuthRedirectionServer.cs:101 
UnityEngine.Debug:LogWarning(Object)
AuthRedirectionServer:Listen() (at Assets/GoogleDrive/AuthRedirectionServer.cs:154)

Maybe this is the cause of the problem ?

**Comment by GuillermoDoradoVide** [comment]
Solved! I don´t know why (becouse It was working until this error happened). Leaving the ClientSecret blank 
**drive.ClientSecret = "";** did the trick.
