### ISSUE TITLE
파일 리스트를 못 불러옵니다.

### ISSUE THREAD

**Issue by kanious** [midworld/unity-googledrive#39]
안녕하세요.
유니티 2017로 안드로이드 어플을 개발하고 있습니다.
개인 구글 계정으로 접속까지는 성공한 상태입니다.
현재 구글 드라이브에 여러 개의 파일과 폴더가 있는데, 하나도 불러오지 못합니다.
코드는 아래와 같습니다.
![aaa](https://user-images.githubusercontent.com/37854837/38298687-0621c860-3833-11e8-9c9b-66730653d091.png)

파일이 있는 경우 foreach문까지 잘 들어가는데, 문제는 기존의 파일을 전혀 불러오지 못하네요..
![bbb](https://user-images.githubusercontent.com/37854837/38298803-620b19b0-3833-11e8-8e70-4137b57dd9c5.png)
file count가 0으로 나옵니다. 실제로는 파일이 여러 개 업로드 되어 있는 상태입니다.
단, drive.InsertFolder("new_folder", null)로 새 폴더를 생성하거나
drive.UploadFile(, )로 업로드한 파일은 드라이브 상에도 잘 생성되며 리스트에도 나타납니다.

![ccc](https://user-images.githubusercontent.com/37854837/38299071-075488fc-3834-11e8-95ce-9005f1c47b8a.png)
코드상에서 insertFolder로 생성 후 동일하게 ListAllFiles() 로 탐색한 내용입니다.
샘플 코드에 있었던 이미지 파일과 텍스트 파일을 업로드했을 때도 둘 다 잘 읽어왔었습니다.

브라우저에서 따로 업로드해 올린 파일 정보만 읽어오지 못하는 것 같은데
어느 부분이 문제인지 도움을 좀 주실 수 있을까요?
감사합니다.

**Comment by midworld** [comment]
안녕하세요.

ListAllFiles()는 q="" 인 files.list 요청과 같습니다. 다음 페이지에서 직접 테스트해보고 결과를 확인해 보시면
됩니다.

https://developers.google.com/drive/v2/reference/files/list

감사합니다.

2018-04-04 18:19 GMT+09:00 kanious <notifications@github.com>:

**Comment by kanious** [comment]
Google Drive API만 추가하고 Google+API 는 추가를 안 해서 생기는 문제였네요...
해결했습니다! 빠른 답변과 도움 감사드립니다. 좋은 하루 되시길 바랍니다!!
