### ISSUE TITLE
Deleting file taking a long time

### ISSUE THREAD

**Issue by GuyCorbett** [midworld/unity-googledrive#4]
Hi there,

I sent you this message on the Unity forums but don't know if you are active on them so thought I would open it as an issue here too. Sorry if you get this twice as a result.

I've recently been using your Google Drive code in my Unity app and wanted to thank you because it's been absolutely indispensable. However there is one issue I've encountered which I was wondering if you could help me with. I know you wrote the code a while ago but any pointers you could give would be greatly appreciated.

I've got my app uploading to Google Drive, downloading and moving files around all fine. The problem comes when I want to delete something. I'm using your GoogleDriveFile.DeleteFile function and, when I check Google Drive via my web browser, I can see that the file has indeed been deleted. However the function is taking a long time to complete, sometimes over 5 minutes - just to delete a small text file. 

Debugging it the issue seems to be on line 260 of UnityWebResponse.cs;

do
{
    read = bufferedStream.Read(buffer, 0, buffer.Length);
    ms.Write(buffer, 0, read);
} while (read > 0);

That call to bufferStream.Read is taking minutes to return and I really can't see why. If you can shed any light on this I would be much obliged. 

Lastly, you might be interested to learn of a couple of issues I had to work around getting the google drive code to work.

Firstly google drive has dropped the need for a ClientSecret to pair with the ClientID. Your code still connects but only if you set the ClientSecret to string.empty.

Secondly the free version of Unity has dropped support for web sockets on mobile platforms. However there's a very reasonably priced download from the Unity Asset Store called "Good Ol' Sockets" which fixed this for me.

Anyway, thanks again for putting this code out there, it really has made a world of difference to my project.

**Comment by midworld** [comment]
Hello Guy Corbett,

Thank you for using this plugin.

Yes, it is pretty old plugin but it seems Google drive api is not changed.

So I have no idea delete api takes a long time.

But you can try Steam.ReadTimeout property as 15sec or something.

And I didn't see 'Google Ol' Sockets' code but I don't think it support
DELETE/PUT method.

It needs Net.Socket functions.

Thanks.
