### ISSUE TITLE
구글 API인증 중에 Error: redirect_uri_mismatch 라는 에러가 납니다.

### ISSUE THREAD

**Issue by wapj** [midworld/unity-googledrive#5]
안녕하세요~

좋은 플러그인을 만들어주셔서 감사합니다. 
한국 분인것 같아서 한국어로 등록합니다.

DriveTest.cs 에 ClientID와 ClientSecret을 넣고 DriveTest 씬을 실행을 했는데요,
리다이렉트시에 localhost:9271로 리다이렉트 되면서, 아래와 같은 에러가 나는데요,
localhost에 9271 포트로 서버가 떠있어야 하는 것인지요?

400. That’s an error.

Error: redirect_uri_mismatch
Application: companygame
You can email the developer of this application at: 
The redirect URI in the request: http://localhost:9271 did not match a registered redirect URI.

**Comment by midworld** [comment]
안녕하세요.

사용자가 구글 인증을 하면 개발자가 지정한 URI로 인증 코드가 날아오게 됩니다.

해당 URI는 구글 API 콘솔에서 변경 가능합니다.

구글 API 콘솔에서 위 주소를 등록하면 해결될 것입니다.

감사합니다.



2015-02-23 1:47 GMT-08:00 wapj <notifications@github.com>:

**Comment by wapj** [comment]
감사합니다~ 해결했습니다~
OAuth 타입을 '웹 애플리케이션용 클라이언트 ID'로 만들어야 되는군요~
