### ISSUE TITLE
Unable to authorize

### ISSUE THREAD

**Issue by nikescar1** [midworld/unity-googledrive#6]
I know this is old but, there doesn't seem to be another Google Drive Unity plugin, paid, free or otherwise.

The demo apk provided authorizes fine but does not upload files to Drive. I opened the project in Unity 4.6 and built a new apk and I get this error:

06-22 09:59:45.360: E/Unity-GoogleDrivePlugin(28812): checkAuthorized: com.google.android.gms.auth.GoogleAuthException: Unknown

I thought it may have to do with Google changing the authorization scope: https://www.googleapis.com/auth/drive.appdata to https://www.googleapis.com/auth/drive.appfolder

I changed these in the the plugin and rebuilt and imported it into my project and I still can't get authorization. It doesn't even get to the point of asking to choose and email to authorize with.

Do you have any ideas?

**Comment by midworld** [comment]
Hi nikescar1,
Sorry for late response.

I think Google changed OAuth url. I found: https://developers.google.com/identity/protocols/OAuth2UserAgent

> https://accounts.google.com/o/oauth2/auth?
>  **scope=email%20profile&**
>  state=%2Fprofile&
>  redirect_uri=https%3A%2F%2Foauth2-login-demo.appspot.com%2Foauthcallback&
>  response_type=token&
>  client_id=812741506391.apps.googleusercontent.com

But my code:
```
// /Assets/GoogleDrive/GoogleDriveAuthorization.cs:35
return new Uri("https://accounts.google.com/o/oauth2/auth?" +
	"scope=" +
		"https://www.googleapis.com/auth/drive.file" + // <==
		" https://www.googleapis.com/auth/userinfo.email" + // <==
		" https://www.googleapis.com/auth/drive.appdata" + // <==
	"&response_type=code" +
	"&redirect_uri=" + RedirectURI +
	"&client_id=" + ClientID);
```
I think it will work if you modify `// <==` lines to correct string.

I am sorry but very busy now days, so I didn't test this. It is just a *idea*.

Hope you solve this problem.
Thanks!

**Comment by nikescar1** [comment]
Thanks a lot midworld. That should give me a place to start. And thanks for your work on this plugin by the way.

**Comment by msalicefredine** [comment]
@nikescar1 Did you ever get yours working? I'm struggling with the same issue and I'm not sure where to go from here!
