### ISSUE TITLE
Wrong AuthorizationCode

### ISSUE THREAD

**Issue by mihvotak** [midworld/unity-googledrive#7]
From about February 2016 authorization is broken, got "error" : "invalid_grant".
Problem: Google server sends "GET /favicon.ico" request before callback request with auth code.
How to solve:
in AuthRedirectionServer.cs
`						string code = s.Substring(0, s.IndexOf("\r\n")).Split(' ')[1];`
`						// checking if request has auth code`
`						int index = code.IndexOf("/?code=");`
`						if (index == -1)`
`						{`
`							byte[] header404 = Encoding.UTF8.GetBytes(`
`								"HTTP/1.1 404 Not Found\r\n" +`
`								"\r\n\r\n");`
`							stream.Write(header404, 0, header404.Length);`
`							break;`
`						}`
`						// check end`
`						code = code.Substring(index + 7);`
`						AuthorizationCode = code;`

**Comment by Ragzouken** [comment]
Ran into this issue, and this fixes it - thanks!
