### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pointcache** [midworld/unity-googledrive#9]
http://i.imgur.com/AnuwiMT.png

this is the error im getting when trying to connect

**Comment by midworld** [comment]
Hi pointcache,

Did you make a valid client key? I think the following page can help you: http://stackoverflow.com/questions/23775972/error-invalid-client-with-google-apps-api-oauth2

Thanks.

**Comment by pointcache** [comment]
I misunderstood EVERYTHING :D
now i made it work thanks. amazing thing works well.
